

parte1:
	go run parte1.go
parte2:
	go run parte2.go

lisp1:
	sbcl --noinform --load parte1.lisp --non-interactive && printf '\n'
lisp2:
	sbcl --noinform --load parte2.lisp --non-interactive && printf '\n'

